name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.4.2
  - pytest=7.0.1
  - scipy=1.7.3
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
